CREATE TABLE IF NOT EXISTS com_user (
    user_id VARCHAR(20) PRIMARY KEY,
    password VARCHAR(100) NOT NULL,
    user_name VARCHAR(30) NOT NULL,
    dept_name VARCHAR(30),
    pos_name VARCHAR(10),
    email VARCHAR(100),
    office_tel VARCHAR(20),
    cell_tel VARCHAR(20),
    auth VARCHAR(10),
    use_flag SMALLINT,
    dev_grp_no INTEGER,
    auth_grp_no INTEGER,
    manage SMALLINT,
    parent_id VARCHAR(20),
    account VARCHAR(10),
    netis_web_theme VARCHAR(100),
    netis_web_menu_min VARCHAR(5),
    isshare SMALLINT,
    is_recv_email SMALLINT,
    is_recv_sms SMALLINT,
    is_recv_push SMALLINT,
    is_recv_poll SMALLINT,
    user_pic BYTEA,
    messenger SMALLINT,
    send_auth_item VARCHAR(20),
    pass_date TIMESTAMP,
    pass_err_cnt INTEGER,
    dashboard_auth VARCHAR(20),
    news_agency VARCHAR(10),
    minor_poll SMALLINT,
    major_poll SMALLINT,
    critical_poll SMALLINT,
    sms_group INTEGER,
    user_pc_ip VARCHAR(255),
    pass_chg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    topo_auth_grp_no INTEGER,
    pw_salt VARCHAR(50),
    menu_auth_no INTEGER,
    is_reset_pw SMALLINT DEFAULT 1,
    noti_cnt SMALLINT DEFAULT 20,
    sso_yn VARCHAR(1),
    chat_id VARCHAR(50)
);
